spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lyr?serverTimezone=GMT&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true

#  com.mysql.cj.jdbc.Driver
